# window环境

check1: win_check.cpp
	g++ -o win_check win_check.cpp

check2: win_check2.cpp
	g++ -o win_check win_check2.cpp

check3: win_check3.cpp
	g++ -o win_check win_check3.cpp

check4: win_check4.cpp
	g++ -o win_check win_check4.cpp

check5: win_check5.cpp
	g++ -o win_check win_check5.cpp

check6: win_full.cpp
	g++ -o win_check win_full.cpp

check7: win_final.cpp
	g++ -o win_check win_final.cpp

clean:
	del win_check.exe

run:
	chcp 65001
	win_check.exe